// app/layout.tsx
import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./_components/navigantion/Footer";
import { Header } from "./_components/navigantion/Header";
import XmasSnow from "./_components/main/XmasSnow";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* ClerkProvider must wrap everything */}
      <ClerkProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* Global snow effect */}
          <XmasSnow />

          {/* Header always visible */}
          <Header />

          {/* Page content */}
          {children}

          {/* Footer */}
          <Footer />
        </body>
      </ClerkProvider>
    </html>
  );
}
